# Generated by Django 5.2.1 on 2025-05-22 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('closed', 'Закритий'), ('in_progress', 'В роботі')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
