# Generated by Django 5.2.1 on 2025-05-22 17:14

import api.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=api.models.default_location, geography=True, help_text='Точка на карті у форматі GeoJSON (longitude, latitude)', srid=4326, validators=[api.models.validate_location], verbose_name='Координати'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('in_progress', 'В роботі'), ('closed', 'Закритий')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(help_text='Короткий опис інциденту', max_length=200, verbose_name='Назва інциденту'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='api_inciden_status_372bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='api_inciden_created_5e554b_idx'),
        ),
    ]
